# Generated by Django 4.2.5 on 2023-09-26 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=20)),
                ('manufacturer_model', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('needs_replacing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('rental_status', models.CharField(blank=True, max_length=50, null=True)),
                ('bcd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AquaManagement.bcd')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaManagement.customer')),
                ('regulator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AquaManagement.regulator')),
            ],
        ),
        migrations.CreateModel(
            name='RentalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rental_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_scheme', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wetsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=20)),
                ('manufacturer_model', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=100, null=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('regulator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AquaManagement.regulator')),
            ],
        ),
        migrations.CreateModel(
            name='WetsuitOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('age_of_wetsuit', models.IntegerField(blank=True, null=True)),
                ('needs_replacing', models.BooleanField(blank=True, null=True)),
                ('wetsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaManagement.wetsuit')),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrderEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AquaManagement.bcd')),
                ('regulator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AquaManagement.regulator')),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaManagement.rentalorder')),
                ('wetsuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AquaManagement.wetsuit')),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaManagement.rentalorder')),
            ],
        ),
        migrations.CreateModel(
            name='RegulatorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(blank=True, choices=[('First Stage', 'First Stage'), ('Second Stage', 'Second Stage'), ('Third Stage', 'Third Stage')], max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.BigIntegerField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaManagement.regulator')),
            ],
        ),
        migrations.CreateModel(
            name='BCDOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('age_of_bcd', models.IntegerField(blank=True, null=True)),
                ('needs_replacing', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('bcd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaManagement.bcd')),
            ],
        ),
    ]
