# Generated by Django 4.2.5 on 2023-09-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AquaManagement', '0002_rename_regulatordetails_regulatordetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='wetsuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AquaManagement.wetsuit'),
        ),
        migrations.DeleteModel(
            name='RentalOrderEquipment',
        ),
    ]
